kind: ENC[AES256_GCM,data:8GL1pph1,iv:1mh9pArZcsYkwq9hopBB1rxvAN+EZF2bH5eKqXTymcU=,tag:VISIHzrmM/q9I/mjNcacvA==,type:str]
ansible_user: ENC[AES256_GCM,data:gD/5uYmY,iv:pcnCLgRJe5s4a9/X/3BRGlbgplU6TajuImVdXtKcV/E=,tag:eKRNX+VhbL1aitdau1QVrA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:VPCdnHKA,iv:G8uyH2WDzXJPkD3ha+rGWdXrlQcXAwVc4ArEJdbnAbY=,tag:8J7m/Ui6ErLm6ved2JroKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age129gn3vvzvjpjr3ezn25xfrsau0jecym6htyqv6derdpettrvdezq204t4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYVV5M3A1SFBhY0d1KzJM
            UWU5SXlHeThoMFVVSzM4anZYY3dZelExd0Z3ClAwdlJFaldhcTU1YU0xc2tleXli
            dG5lMWswZi92UzhpQUdjdlNRSEFXSVEKLS0tIDNQVFRFNDNhb3Nab1JORWd3d0Zy
            TkpFSkttcmRzRXhmKzNFQ1R5NUJ1dk0KXWsxmVGC1oSI+KEmniq+EGI0hRJ3eM+/
            OHF9Sg/GETP3FKjidAN0MkuaGutQsb2MDpGqhnBNAO8jOtdoF6QWqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-10T00:15:03Z"
    mac: ENC[AES256_GCM,data:3sfU4sp63lLkrAgpnsTpB6B16UUP/BugxRYIxqX3TNzMfhVANJ5hKJO++pPd+Qt+L41Y4NRqc0zcKbIynHkaqy7+bsLRVd+4BVe9nt/zvOYcgAAGFxjXSxFD4tnKFs23s5nnKrHMwyTmCcinDnRoydtatuOEFGH0hhusFn6twes=,iv:RWNcHhHfqsT8zz9u/YvGa8ujNS5FNbCYIU11UnTc8oY=,tag:lkjzx2a5cW2c3tP0adqi3w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
