apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:sHf0qiHN3+wXI03QdGVuY1nOsJrkYO8M,iv:pCEXx5jDBzT7RFPr6ucuUMMji3QGj349x36PNqQoRGE=,tag:LCad3UpqDOjMdr3IXk236Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age129gn3vvzvjpjr3ezn25xfrsau0jecym6htyqv6derdpettrvdezq204t4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPb0dpWUZoM2d4MjhERkth
            V2VFcVJYdUxNdlZVcWtNblgrUkFFRGlTSlZrCk1URnp0NUhZRFNwK2dLVStYMFZu
            N2ZRbGtybU10bXFCSUNsOGtHYk9OK1kKLS0tIDVIZG1uMGMwbTZrYnM4bFEwTjBj
            dk1uVDN5OFhYVzBrdHE0MURGblBzRW8KYo2dLUP3HjEzKBiM2Kr7T24SFCYPhizH
            lM3ADoifvFLitrQ7CbkfrSWUuwJ7QlnuT+KlneL4LJ1nzdP/EIVUHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-09T03:51:33Z"
    mac: ENC[AES256_GCM,data:dGllUaab/wrbsEANBOtIMUC5CtmNJcn9WRAA4zi6ehZgscue0Hg3rBmSUhLpIWmNsz+//zaJgSbHbi0MKoE4vQyv0fkk64vA6SIo2q5gkKIHJZxcZVzqNv2OwzJMd8jOmXzSSsaAM7dYXWVrOvpK+MR9Qq/oA7Jy7kN8h/sSCks=,iv:lntFEQBdAP7ZnC6g+nPp/4a2UeplkpIZWgPI/ZzbkR0=,tag:yvvIsRgo9aZ4WuxjSPdOnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
