apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:mzAOfss=,iv:KvUvqAZ4j1Ew7Yxpn+RinUcBHcQR60EXC1MwQHQDlC8=,tag:d1BlXSWkAx5e/U+droEUmA==,type:str]
    password: ENC[AES256_GCM,data:09nnP8rI4ZBWrdByurKPZOITvo9RluWdmIvD5CK7Hwbau8vEGvjvDtuUNIckN/r9EHu0FgjmV3tLGKze,iv:8PLxDPqcLB55JnyZP/llV0UwweZDgjMsdpUtxxZFwQM=,tag:YArqKX/QDnULDXVmX3NmLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age129gn3vvzvjpjr3ezn25xfrsau0jecym6htyqv6derdpettrvdezq204t4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOEEwOHd3dVVtbzZMMU43
            S0tPRTkvdnlBVXNvYUtEMzNOaEtSdmt2K2lzCmtNZDNiNjY2dHNrRlo5NHlZY1Qz
            V1YrbXhVcDEySmZhU3BsWFk2NzRuMFEKLS0tIDNpSzhWb2tMODJxV090UUkwZGdS
            SGVXN2M4TUJUbkl0dVRiNkRiamllTXcKxnIGCk279oSwGKlsHQMf7td3PEmtx5Xm
            QirchK5RsvPTgtdHHnzsDNe5jNdmM+MrORFl0EdpzH5gzQ3KPKpfYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-10T00:15:04Z"
    mac: ENC[AES256_GCM,data:n4D4zKm3nOfcFDR/HFPIC72VXbt0y7ddEzWbCYIjFYDtRn5+SB3DxgKbclx4FA4WWm3aNqTpNqsDcbdRCELdAJ8xosYUrH4EVufW0r/4Dxs45DAgtLTY/HD+0MEUSTReDZhP7UahA1c1qxNXMYmkvThjYCEcVtkNrpVESAU4GUE=,iv:pM0nPUX3/DqkhYYIIXoChRH/oCq0/vKrRaI9ULX7X0c=,tag:a1j6DDcrkPRvM83FtWQwmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
